trigger:
  tags:
    include:
      - 'v*'

pool:
  vmImage: 'ubuntu-22.04'

#variables:
#  - name: DOTNET_SDK_VERSION_LTS
#    value: '6.x'
#  - name: DOTNET_SDK_VERSION_STS
#    value: '7.0.100'

steps:
  - checkout: self
    fetchDepth: 3
    submodules: true

  #  - task: UseDotNet@2
  #    displayName: Setup .NET SDK (LTS)
  #    inputs:
  #      version: ${{ variables.DOTNET_SDK_VERSION_LTS }}

  #  - task: UseDotNet@2
  #    displayName: Setup .NET SDK (STS)
  #    inputs:
  #      version: ${{ variables.DOTNET_SDK_VERSION_STS }}

  #  - task: Cache@2
  #    displayName: Cache
  #    inputs:
  #      key: 'nuget | "$(Agent.OS)" | global.json'
  #      restoreKeys: |
  #        nuget | "$(Agent.OS)"
  #        nuget
  #      path: '$(Pipeline.Workspace)/.nuke/temp'
  #    continueOnError: true

  - task: Bash@3
    displayName: Nuke
    inputs:
      targetType: filePath
      filePath: ./build.sh

  - task: PublishBuildArtifacts@1
    displayName: Artifacts
    inputs:
      PathtoPublish: output