services:
  instance:
    container_name: W0
    build:
      context: /
      dockerfile: src/Web/Dockerfile
    working_dir: /app
    restart: unless-stopped
    privileged: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:5000/tcp
      - 443:5001/tcp