blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/ennerperez/ddd-mvc-web/discussions/new
    about: Ask a question or request support for using the template