name: Build

trigger:
  - master

pool:
  name: Azure Pipelines

variables:
  BuildRuntime: 'linux-x64'
  DefaultContext: 'DefaultContext'

steps:
  - checkout: self
    submodules: true
    persistCredentials : true
      
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: 6.x

  - task: DotNetCoreCLI@2
    displayName: 'Add New Migration'
    inputs:
      command: custom
      custom: ef
      arguments: 'migrations add $(Build.BuildNumber) -o "Migrations/Default" --context $(DefaultContext)  --project src/Persistence --startup-project src/Web '
    enabled: false

  - task: DotNetCoreCLI@2
    displayName: '.NET Publish'
    inputs:
      command: publish
      arguments: '--configuration $(BuildConfiguration) --framework net6.0 --runtime $(BuildRuntime) --no-self-contained --output $(build.artifactstagingdirectory) '

  - task: pekspro.pekspro-efcore-migration-script-generator.efcore-migration-script-generator.efcore-migration-script-generator-task@1
    displayName: 'Generate Migration Scripts'
    inputs:
      projectpath: src/Persistence/Persistence.csproj
      databasecontexts: $(DefaultContext)
      startupprojectpath: src/Web/Web.csproj
      targetfolder: '$(build.artifactstagingdirectory)/Migrations'
      installdependencies: false
    enabled: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'

