<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\src\.imports\Template.props"/>
  <Import Project="..\..\src\.imports\Template.targets"/>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
