name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
        
env:
  DOTNET_SDK_VERSION: '6.x'

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          
      - name: Setup EF
        run: dotnet tool install --global dotnet-ef
          
      - name: Nuke
        run: ./build.sh

      - name: Migration
        run: dotnet ef migrations script -i --context DefaultContext -o build/Migrations.sql --project src/Persistence --startup-project src/Web

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            build/Migrations.sql
            build/Release.zip
          if-no-files-found: error

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          bodyFile: CHANGELOG.md
          artifacts: |
            build/Migrations.sql
            build/Release.zip
            
  deploy:
    name: Deploy
    needs: build
    environment:
      name: 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact