name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

#env:
#  DOTNET_SDK_VERSION_LTS: '6.x'
#  DOTNET_SDK_VERSION_STS: '7.0.100'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 3

      #      - name: Setup .NET SDK (LTS)
      #        uses: actions/setup-dotnet@v3
      #        with:
      #          dotnet-version: ${{ env.DOTNET_SDK_VERSION_LTS }}

      #      - name: Setup .NET SDK (STS)
      #        uses: actions/setup-dotnet@v3
      #        with:
      #          dotnet-version: ${{ env.DOTNET_SDK_VERSION_STS }}

      #      - name: Cache
      #        uses: actions/cache@v3
      #        with:
      #          path: |
      #            .nuke/temp
      #            ~/.nuget/packages
      #          key: ${{ runner.os }}-${{ hashFiles('global.json', 'source/**/*.csproj') }}

      - name: Permissions
        run: chmod +x build.sh

      - name: Nuke
        run: ./build.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            output/*.nupkg
          if-no-files-found: warn

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            output/*.zip
          if-no-files-found: warn

  deploy:
    name: Deploy
    needs: Build
    environment:
      name: 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          artifacts: |
            *.nupkg
            *.zip