name: .NET

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore tools
        run: dotnet tool restore
        working-directory: "/home/runner/work/solution/solution"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: "/home/runner/work/solution/solution/src"

      - name: Build solution
        run: dotnet build --no-restore
        working-directory: "/home/runner/work/solution/solution/src"

      - name: Cake build
        run: dotnet tool run dotnet-cake
        working-directory: "/home/runner/work/solution/solution"